### PR TITLE
You'll hate me: Fix inverter settings once an for all by ...

### PR DESCRIPTION
**Pull request by RustyDust**
- removing the kludge from `updateData`and expanding the code in `AddOrUpdateEntities` to properly handle `fac` in different locations
- reorder all settings formerly looked up in `inverter` to try `battery_system['grid_information']` first since modern sonnenBatteries seem to have moved them there. One `if` less to process per roundtrip ;)
- clean up the code where we have multilple possibilities to not duplicate definitions
- add checks for `ppv` amd `upv` in `battery_system['grid_information']` because that's where those settings are on my system ;)

### CODE REVIEW

**Comment by jepperc** [comment]
I will test this out today, so lets not merge until I do :D

**Comment by jepperc** [comment]
Seems to work fine! :) All values are there with ppv, ipv and upv for both 1 and 2, and they seem to match what was there before, so not reading something wrong.

**Comment by RustyDust** [comment]
> Seems to work fine! :) All values are there with ppv, ipv and upv for both 1 and 2, and they seem to match what was there before, so not reading something wrong.

Phew ;) Did you check `fac` too because that's the one the kludge was originally introduced for (works for me but ...)? Also, if you don't mind, I'd be really interested to see a full dump from your system for I'm curious whether there are other variables not exported by my setup and also whether there are some others populated that are always '0' for me.

**Comment by jepperc** [comment]
Fac is good too.
No idea how to get a full dump.. debug logging doesnt give any outputs when there are no errors? :P

**Comment by jepperc** [comment]
https://pastebin.com/qPfaZL9v
There are some 0 values like IPV2 but thats because of no sun right now :)

**Comment by jepperc** [comment]
> Oh, wow. Your inverter section looks quite different from [my Inverter output](https://gist.github.com/RustyDust/4b685b855c76d1c7acf0c88a2473b536)

Wow.. In my mind these are two seperate integrations almost :D

**Comment by weltmeyer** [comment]
Also, for me:
LogIn with installer allows me to directly access the integrated inverter under http://sonnenIP:7980/page.main.html

**Comment by weltmeyer** [comment]
image

**Comment by weltmeyer** [comment]
image

**Comment by RustyDust** [comment]
> LogIn with installer allows me to directly access the integrated inverter

Now I'd only need the installer login for my installation ;) Btw: Thanks for the inspiration and the. blueprint on how to write HA integrations -> https://github.com/RustyDust/ha_sonnencharger

**Comment by weltmeyer** [comment]
you could try this one
image

**Comment by RustyDust** [comment]
Tried and failed ;) Thanks nevertheless.

**Comment by TobyRh** [comment]
> you could try this one image

@weltmeyer you just gave me the keys to the castle 🔑

**Pull request merged**
