### PR TITLE
Introduce "debug_mode" and ...

### PR DESCRIPTION
**Pull request by RustyDust**
- reduce logging (not data output) if debug_mode is false (default)
- allow changing of debug_mode in options panel
- change URL in manifest to point to github page
- add translation for new debug_mode option
- change logic for 'fac' detection
- in case of active debug_mode write all settings to log
- Add info about 'Warnings' to README.md
- remove some more "try/except" ;)

### CODE REVIEW

**Comment by jepperc** [comment]
@weltmeyer @RustyDust  PPV2 and all the new things are not working anymore after this merge :(

**Comment by RustyDust** [comment]
Can you send a log? Preferably with debug enabled.

**Comment by RustyDust** [comment]
Reason I ask is: My Sonnebatterie doesn't provide `ppv` so I can't check. From looking at the code I see no reason why it should have stopped working.

**Comment by jepperc** [comment]
Regular log:
> 2023-01-05 19:55:28.586 WARNING (Thread-6 (watcher)) [custom_components.sonnenbatterie] No 'ppv2' in inverter -> sensor disabled
2023-01-05 19:55:28.586 WARNING (Thread-6 (watcher)) [custom_components.sonnenbatterie] No 'ipv' in inverter -> sensor disabled
2023-01-05 19:55:28.586 WARNING (Thread-6 (watcher)) [custom_components.sonnenbatterie] No 'ipv2' in inverter -> sensor disabled
2023-01-05 19:55:28.586 WARNING (Thread-6 (watcher)) [custom_components.sonnenbatterie] No 'upv' in inverter -> sensor disabled
2023-01-05 19:55:28.586 WARNING (Thread-6 (watcher)) [custom_components.sonnenbatterie] No 'upv2' in inverter -> sensor disabled

**Comment by jepperc** [comment]
Debug log:
https://pastebin.com/Afjv4uph

So the values are obviously not  where being looked for.. But they were where I got them from in my PR, with values showing up in HA.
Something else must have changed?

**Comment by jepperc** [comment]
I'm thinking line 166 in sensor.py.. the movement of inverter['status']['status']. I can't think of anything else.

**Comment by jepperc** [comment]
Also getting an error when trying to add this integration to a clean HA now..
Config flow could not be loaded: {"message":"Invalid handler specified"}
Something wrong with the new config thing?

**Comment by weltmeyer** [comment]
Status always exists in status...

**Comment by weltmeyer** [comment]
image

**Comment by weltmeyer** [comment]
fixed in bce3747534d4173bde15a130a632cfad18c2c059

**Comment by RustyDust** [comment]
> Status always exists in status...

Not really, seems to depend on the firmware:

```
curl -s  http:/192.168.27.21/api/v1/status | jq
{
  "BackupBuffer": "20",
  "BatteryCharging": false,
  "BatteryDischarging": false,
  "Consumption_Avg": 3241,
  "Consumption_W": 3261,
  "Fac": 50.020999908447266,
  "FlowConsumptionBattery": false,
  "FlowConsumptionGrid": true,
  "FlowConsumptionProduction": false,
  "FlowGridBattery": false,
  "FlowProductionBattery": false,
  "FlowProductionGrid": false,
  "GridFeedIn_W": -3260,
  "IsSystemInstalled": 1,
  "OperatingMode": "2",
  "Pac_total_W": 0,
  "Production_W": 0,
  "RSOC": 26,
  "RemainingCapacity_Wh": 15576,
  "SystemStatus": "OnGrid",
  "Timestamp": "2023-01-05 22:10:19",
  "USOC": 20,
  "Uac": 236,
  "Ubat": 208,
  "dischargeNotAllowed": false,
  "generator_autostart": false,
  "NVM_REINIT_STATUS": 0
}
```

Anyway, sorry for the disruption there.

**Comment by weltmeyer** [comment]
Interesting... i am using 
/api/inverter without the v1.
v1 is giving me a 404

**Pull request merged**
